version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  app:
    build: .
    container_name: node-express-mongoose-todo-api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
